<MainScreen@MDScreen>:
    MDFloatLayout:
        MDLabel:
            id: display
            text: "Hello"
            halign: "center"
            pos_hint: {"center_x": .5, "center_y": .6}
            font_name: 'NotoSansKR-Bold.otf'
            font_size: "40sp"
        MDIconButton:
            icon: "language-python"
            pos_hint: {"center_x": .5, "center_y": .4}
            on_release: app.get_data()

