<MainScreen@MDScreen>:
    MDFloatLayout:
        Image:
            id: img
        MDLabel:
            id: display
            text: "Nice to Meet You"
            halign: "center"
            pos_hint: {"center_x": .5, "center_y": .6}
            font_size: "40sp"
        MDIconButton:
            icon: "language-python"
            pos_hint: {"center_x": .5, "center_y": .4}
            on_release: app.get_data()

